name: Build and publish

on:
    push:
        branches: [main]
jobs:
    build-and-push:
        runs-on: ubunut-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        -name: Set up Docker buildx
         uses: docker/setup-buildx-action@v2
        
        -name: login to Docker Hub
         uses: actions/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

        -name: Build and push
         uses: build-push-actions@v5
        with:
          context: .
          push: true
          tags: luxra76/bookstore-API